### ISSUE TITLE
Monster evolution not respecting custom 'Start of Cataclysm'/'Fall of Civilization' date

### ISSUE THREAD

**Issue by sick-trigger** [Cataclysm-TLG/Cataclysm-TLG#813]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

Monster evolution acts as if the cataclysm always occurs on the default date, even if changed at character creation
maybe related to https://github.com/CleverRaven/Cataclysm-DDA/issues/80959? but couldn't reproduce it on latest DDA

### Steps To Reproduce

1. Start new character in new world, with later Cataclysm, Fall of Civ and Game Start dates
i.e. instead of 'Year 1 **Spring**, day 41/61', set all three to 'Year 1 **Winter**, day 41/61'
2. Save and quit, exit the game
4. Restart game, load the save and walk to town
5. Lots of scary zombies

### Expected behavior

Monster evolution should be roughly the same as with default starting dates, as the same amount of time has passed since cataclysm/fall of civilization

### Game version

- OS: Windows
    - OS Version: 10.0.19045.5854 (22H2)
- Game Version: 2025-05-23-0559 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    The Last Generation [tlg],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by worm-girl** [comment]
Might be fixed by DDA 81005, which is not yet merged.

**Comment by worm-girl** [comment]
Fixed

**Comment by sick-trigger** [comment]
still occuring on latest relese!! same steps to reproduce, fully restarting the application is necessary to notice the boosted zombies

**Comment by worm-girl** [comment]
Fixed for real real.
